### ISSUE TITLE
RabbitMQ configuration failure with version  1.5.0.RELEASE for service registery

### ISSUE THREAD

**Issue by avirkar** [pivotal-cf/spring-cloud-services-starters#15] opened 2017-11-15 15:30 UTC
My application uses the 1.5.0.RELEASE for service registry depencency. Whenever I deploy the application to PCF the application is unable to create any exchange or queues.  It works well with 1.4.0.RELEASE so i think something in the latter release is breaking it. I also noticed that having the connection params for rabbit (host, port, virtualhost, username, password) in the user provided environment variables resolves the issue but that is not the right way to do it. 

`<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-amqp</artifactId>
</dependency>`

`<dependency>
			<groupId>io.pivotal.spring.cloud</groupId>
			<artifactId>spring-cloud-services-starter-service-registry</artifactId>
			<version>1.5.0.RELEASE</version>
		</dependency>`

**Comment by scottfrederick** [comment] 2017-11-15 16:16
@avirkar Please share the full `<dependencies>` and `<dependencyManagement>` sections from your pom.xml so we can see the versions of Spring Boot, Spring Cloud, and Spring Cloud Services libraries you are using. There might be an issue with the compatibility of the versions being used. See the [Spring Cloud Services docs](http://docs.pivotal.io/spring-cloud-services/1-4/common/client-dependencies.html) for the recommended dependencies configuration. 

It would also be helpful to see the `VCAP_SERVICES`  JSON for the app that is trying to use the service registry and RabbitMQ service (with credentials redacted as necessary).

**Comment by avirkar** [comment] 2017-11-17 23:34
The following is my pom file. `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId></artifactId>

	<name></name>
	<description></description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.8.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<axon.version>3.0.6</axon.version>
		<logback.version>1.2.3</logback.version>
		<logstash-logback-encoder.version>4.11</logstash-logback-encoder.version>
		<swagger.version>2.7.0</swagger.version>
		<ehcache.version>2.8.3</ehcache.version>
		<cucumber.version>1.2.5</cucumber.version>
		<commons-io.version>2.5</commons-io.version>
		
		<qpid-broker.version>6.1.4</qpid-broker.version>
		
		<preopen.common.version>1.0.0</preopen.common.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-rest</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-amqp</artifactId>
		</dependency>

		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>

		
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-support</artifactId>
		</dependency>

		
		<dependency>
			<groupId>io.pivotal.spring.cloud</groupId>
			<artifactId>spring-cloud-services-starter-service-registry</artifactId>
			<version>1.4.0.RELEASE</version>
		</dependency>

		

		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<exclusions>
				<exclusion>
					<groupId>com.vaadin.external.google</groupId>
					<artifactId>android-json</artifactId>
				</exclusion>
			</exclusions>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>${commons-io.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.qpid</groupId>
			<artifactId>qpid-broker</artifactId>
			<version>${qpid-broker.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.apache.geronimo.specs</groupId>
					<artifactId>geronimo-servlet_3.0_spec</artifactId>
				</exclusion>
			</exclusions>
		</dependency>


		

		
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>

		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>

		
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
		</dependency>

		

		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>${logstash-logback-encoder.version}</version>
		</dependency>

		

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>${swagger.version}</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>${swagger.version}</version>
		</dependency>


	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Camden.SR7</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>


	<build>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>pl.project13.maven</groupId>
				<artifactId>git-commit-id-plugin</artifactId>
			</plugin>
		</plugins>

	</build>

</project>
`

**Comment by scottfrederick** [comment] 2017-11-17 23:54
@avirkar The first thing to try is to remove the `<version>` element from this block: 

```
	<dependency>
		<groupId>io.pivotal.spring.cloud</groupId>
		<artifactId>spring-cloud-services-starter-service-registry</artifactId>
		<version>1.4.0.RELEASE</version>
	</dependency>
```

and add this block to the `<dependencyManagement>` section: 

```
            <dependency>
                <groupId>io.pivotal.spring.cloud</groupId>
                <artifactId>spring-cloud-services-dependencies</artifactId>
                <version>1.4.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

If you change the `spring-cloud-services-dependencies` version from `1.4.0.RELEASE` to `1.5.0.RELEASE`, you could try to also change the `spring-cloud-dependencies` from `Camden.SR7` to `Dalston.SR4` to see if you are running into version compatibility problems.

**Comment by pavax** [comment] 2018-01-31 14:07
I have the same problem. Looks like it's caused by 

`io.pivotal.spring.cloud.config.java.ServiceInfoPropertySourceAdapter.java` (1.6.1)

**Comment by spikymonkey** [comment] 2018-03-07 15:02
Thanks for the report @avirkar, and for the follow-up @pavax. As you say, this seems to be an issue in the connector, so I'm going to close this issue in favour of https://github.com/pivotal-cf/spring-cloud-services-connector/issues/36.

**Closed by spikymonkey** 2018-03-07 15:02 UTC
