### ISSUE TITLE
Config server 401 when setting spring.config.import as environment variable

### ISSUE THREAD

**Issue by mrodal** [pivotal-cf/spring-cloud-services-starters#428] opened 2024-07-08 22:14 UTC
### Describe the bug

When setting environment variable `SPRING_CONFIG_IMPORT` instead of using application.properties, OAuth2ConfigDataLocationResolver fails to register the `OAuth2ConfigClientRequestTemplateFactory`

### Reproduction steps

1. Set env var SPRING_CONFIG_IMPORT instead of using application.properties
2. Try to start application
3. You get a 401 error

### Expected behavior

It should use the oauth2 config

### Additional context

Debugging I found that the difference is that when using the application.properties, `OAuth2ConfigDataLocationResolver.isResolvable` is first called with the properties files as location:

![image](https://github.com/pivotal-cf/spring-cloud-services-starters/assets/20667544/caaffffd-d9ea-43da-9532-4e506ca09793)

And then with the location from spring.config.import:

![image](https://github.com/pivotal-cf/spring-cloud-services-starters/assets/20667544/8374eb11-a063-47d6-a8cc-3d2623a451d7)

When using the environment variable, its the other way around, and in the first call with the `configserver:` location, it doesnt find of the oauth configuration from the properties file and registers the non-oauth `ConfigClientRequestTemplateFactory`.

**Comment by kvmw** [comment] 2024-07-09 07:03
@mrodal  could you please share a sample configuration? 

I assume you are using `SPRING_CONFIG_IMPORT` to import another property file. If this is the case, where do you specify the config server url? (`spring.config.import=configserver:foo.url`)

**Comment by mrodal** [comment] 2024-07-09 10:14
Sure, here's a sample configuration file:
```yaml
spring:
  application:
    name: sample-application
  cloud:
    config:
      client:
        oauth2:
          client-id: (...)
          client-secret: (...)
          access-token-uri: (...)
          scope: (...)
    stream:
      kafka:
        binder:
          brokers: http://localhost:9092
```
`SPRING_CONFIG_IMPORT=configserver:http://localhost:1984`

We set that env var following the suggestion in [this thread](https://github.com/spring-cloud/spring-cloud-config/issues/1877#issuecomment-840311167) because SCC was breaking our tests

**Comment by kvmw** [comment] 2024-07-29 13:50
Fixed in v4.1.4

**Closed by kvmw** 2024-07-29 13:50 UTC
Labels: bug

**Comment by mrodal** [comment] 2024-07-29 17:03
Thanks @kvmw 
Im trying it out but im seeing weird behaviour.

First of all, the workaround I was using in the meantime was setting the oauth properties as environment variables as well:
```env
SPRING_CONFIG_IMPORT=configserver:http://config-server.internal/
SPRING_CLOUD_CONFIG_CLIENT_OAUTH2_CLIENT-ID=<clientid>
SPRING_CLOUD_CONFIG_CLIENT_OAUTH2_CLIENT-SECRET=<secret>
SPRING_CLOUD_CONFIG_CLIENT_OAUTH2_ACCESS-TOKEN-URI=<token uri>
SPRING_CLOUD_CONFIG_CLIENT_OAUTH2_SCOPE=<scope>
```

With the new code, it seems like the `OAuth2AuthorizedClientHttpRequestInterceptor` interceptor is being added twice to the RestTemplate, and the Authorization header is being duplicated:
![image](https://github.com/user-attachments/assets/59a2c4e9-81d0-44d8-9eb9-4932711c1c32)


Removing the variables from env and setting them a properties, I get a 401 error, 

With both approaches, I see that before requesting the config for the application with correct name (`http://config-server.internal/the-real-application-name/default`) I see a request is being made for the config for an application named 'application" (`http://config-server.internal/application/default`).

The 401 error is because the request to the "application" named application does not include the authorization jwt

The logs show that theres 2 requests for the config:
```
INFO restartedMain o.s.c.c.c.ConfigServerConfigDataLoader - Fetching config from server at : http://config-server.internal/
INFO restartedMain o.s.c.c.c.ConfigServerConfigDataLoader - Fetching config from server at : http://config-server.internal/
```

**Comment by kvmw** [comment] 2024-07-30 09:44
@mrodal 
Regarding duplicate interceptors, you are right. Unfortunately our tests was not covering this case. But this should not impact the behaviour and authentication should be successful. I am going to fix this for the next patch release. 

Duplicate calls are the expected behaviour of Spring Cloud Config Client. 
The first call is triggered by `SPRING_CONFIG_IMPORT=configserver: ...` environment variable and at that point application properties (local properties in the classpath) are not loaded yet. so application name, profile and label are the default values.  In the second call those properties are loaded and you should see them being used in the call. If the oauth properties are provided by `application.properties` , the first all will fail (401) but the second call should be successful.

**Comment by kvmw** [comment] 2024-07-30 14:19
@mrodal 
I've pushed a change which prevents duplicate interceptor registration. would you be able to test the changes before I release them? 
you should be able to build the library locally by running `./gradlew clean build publishToMavenLocal`

**Comment by mrodal** [comment] 2024-07-30 15:30
thank you, I'll test it and let you know as soon as I can

**Comment by mrodal** [comment] 2024-07-30 17:24
It now works perfectly using env vars for all the configuration ✅

Setting the oauth in the properties keeps working as before this last fix: 2 requests (expected as you mention), one fails, the other is successful, application crashes.

```
ERROR restartedMain o.s.boot.SpringApplication - Application run failed org.springframework.cloud.config.client.ConfigClientFailFastException: Could not locate PropertySource and the resource is not optional, failing
```

Setting the config server as optional allows the application to start, but I would like it to not be optional because the remote config is mandatory for the application to run properly

**Comment by kvmw** [comment] 2024-07-31 08:13
Thanks for try the fix. I will release a new patch version with this fix. 

Can you explain a little more about your remaining issue? 

My understanding is that your client application requires (mandatory) configuration from the config server but config server is not available in your local env? Am I right?

**Comment by mrodal** [comment] 2024-07-31 10:44
Sure, the problem comes up with the same configuration as in the original issue, with the combination of
```env
SPRING_CONFIG_IMPORT=configserver:http://config-server.internal/
```
and 
```yaml
spring:
  cloud:
    config:
      client:
        oauth2:
          client-id: (...)
          client-secret: (...)
          access-token-uri: (...)
          scope: (...)
```

With this, the application crashes on startup because two requests are made to the config server:
1. first without the application properties: fails with 401
2. second one with the application properties: successful

Even though the second one is successful, it seems to be too late because the application crashes due to the first one failing.
The error mentions `ConfigClientFailFastException: Could not locate PropertySource and the resource is not optional` so I tried marking the remote config as optional:
```env
SPRING_CONFIG_IMPORT=optional:configserver:http://config-server.internal/
```
And then it works, but it should not be optional because the application wont function without it

Here's the full stacktrace

```
2024-07-30 14:21:30.019 INFO restartedMain o.s.c.c.c.ConfigServerConfigDataLoader - Fetching config from server at : http://config-server.internal/  
2024-07-30 14:21:30.020 INFO restartedMain o.s.c.c.c.ConfigServerConfigDataLoader - Fetching config from server at : http://config-server.internal/  
2024-07-30 14:21:30.020 INFO restartedMain o.s.c.c.c.ConfigServerConfigDataLoader - Located environment: name=sample-application, profiles=[default], label=null, version=30cda5e6e79227d42e7a418f50a4de36555db470, state=null  
2024-07-30 14:21:30.131 ERROR restartedMain o.s.boot.SpringApplication - Application run failed org.springframework.cloud.config.client.ConfigClientFailFastException: Could not locate PropertySource and the resource is not optional, failing
  at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.doLoad(ConfigServerConfigDataLoader.java:201)
  at org.springframework.cloud.config.client.ConfigClientRetryBootstrapper.lambda$initialize$1(ConfigClientRetryBootstrapper.java:54)
  at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.load(ConfigServerConfigDataLoader.java:92)
  at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.load(ConfigServerConfigDataLoader.java:61)
  at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:96)
  at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:132)
  at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:87)
  at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:121)
  at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:245)
  at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:232)
  at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:96)
  at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
  at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
  at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
  at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
  at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
  at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
  at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
  at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
  at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
  at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:370)
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
  at com.santander.notifications.AppStarter.main(AppStarter.java:19)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
Caused by: org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 : "{"errors":[{"code":"CCCS_GEN_003","message":"Auth error","level":"ERROR","description":"Full authentication is required to access this resource"}]}"
  at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:106)
  at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183)
  at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
  at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
  at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:942)
  at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:891)
  at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790)
  at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:672)
  at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.getRemoteEnvironment(ConfigServerConfigDataLoader.java:330)
  at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.doLoad(ConfigServerConfigDataLoader.java:119)
  ... 34 common frames omitted
```

**Comment by kvmw** [comment] 2024-07-31 12:45
This is the limitation of Spring Cloud Config and unfortunately it cannot be addressed in this library. 

We can reproduce the same issue without using the starters library. 
We can configure the **server** with a non-existing default label like `spring.cloud.config.server.git.default-label=wrong-label` and the **client** with the correct label  like `spring.cloud.config.label=main`. With this setup if we put the server url in the properties file (`spring.config.import=configserver:http://config-server.internal/`) the startup would be successful because there is only one call to the server which happens with the proper label (`main`). But if we take the server address out of properties file and pass it as an environment variable the app will crash because the first call relies on the default label provided by server which does not exist, despite the fact that the second call is successful. 

I'd suggest taking this issue to [Spring Cloud Config](https://github.com/spring-cloud/spring-cloud-config/issues) repo and asking for feedback there.
