### ISSUE TITLE
SCS Starters 2.1.0.RELEASE build against Greenwich.RC2

### ISSUE THREAD

**Issue by habuma** [pivotal-cf/spring-cloud-services-starters#61] opened 2019-02-15 22:04 UTC
Although Connectors are building against Greenwich.RELEASE, starters refer to Greenwich.RC2. This may result in some users having the wrong version of Spring Cloud in their project.

The workaround (I think) is to have them explicitly declare Greenwich.RELEASE in their own build.

Should we cut a new starters release to fix this? And, if so, should we also cut a connectors release so that the versions are in sync?

**Comment by royclarkson** [comment] 2019-02-25 19:35
Duplicate of #60

**Closed** 2019-02-25 19:55 UTC
Labels: bug
